title: callistajosette
logo: /assets/img/boids.gif
description: Software Engineer & Aspiring Security Analyst
description: >
  Software Engineer & Security Analyst
  <br>
  <br>
  <a href="https://github.com/callistajosette" target="_blank">ğŸ’» Github</a>
  <br>
  <a href="https://www.linkedin.com/in/callistahoxie" target="_blank">ğŸ“ LinkedIn</a>
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
plugins:
  - jekyll-redirect-from
